export enum PedidoStatus {
  AGUARDANDO_PREPARO = "AGUARDANDO_PREPARO",
  EM_PREPARO = "EM_PREPARO",
  FINALIZADO = "FINALIZADO",
  SAIU_PARA_ENTREGA = "SAIU_PARA_ENTREGA",
  CHEGOU_NO_ENDERECO = "CHEGOU_NO_ENDERECO",
}
